[package]

name = "simplemozjs"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
edition = "2018"
publish = false

[[bin]]
name = "servo"
path = "main.rs"
bench = false

[dependencies]
js = { package = "mozjs", git = "https://github.com/servo/rust-mozjs" }
